// frontend/src/pages/RegisterPage/RegisterPage.jsx
import React, { useEffect, useState } from 'react';
import { new_user } from "../../api/index.js";
import { useNavigate } from 'react-router';
import { auth } from '../../api/firebase-config.js';

const RegisterPage = () => {
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [email, setEmail] = useState('');
    const navigate = useNavigate();

    const handleRegister = async (event) => {
        event.preventDefault();  // Prevent the form from submitting the traditional way
        console.log('Username:', username);
        console.log('Password:', password);
        console.log('Email:', email);

        try {
            await new_user(username, email, password);
            navigate("/login");
        } catch (err) {
            console.log(err);
        }
    };

    useEffect(() => {
        if (auth.currentUser) {
            navigate("/")
        }
    })

    return (
        <div className="register-page">
            <h1 style={{ fontWeight: 'bold', fontStyle: 'italic' }}>Register</h1>
            <form onSubmit={handleRegister}>
                <div className="form-group">
                    <label htmlFor="username">Username:</label>
                    <input
                        type="text"
                        id="username"
                        placeholder="Enter your username"
                        value={username}
                        onChange={(e) => setUsername(e.target.value)}
                        required
                    />
                </div>
                <div className="form-group">
                    <label htmlFor="password">Password:</label>
                    <input
                        type="password"
                        id="password"
                        placeholder="Enter your password"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        required
                    />
                </div>
                <div className="form-group">
                    <label htmlFor="email">Email:</label>
                    <input
                        type="email"
                        id="email"
                        placeholder="Enter your Email"
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        required
                    />
                </div>
                <button type="submit" className="register-button">
                    Register
                </button>
            </form>
        </div>
    );
};

export default RegisterPage;

// frontend/src/components/RegisterPage.vue
<template>
  <div class="register-page">
    <h1 style="font-weight: bold; font-style: italic;">Register</h1>
    <form @submit.prevent="handleRegister">
      <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" id="username" placeholder="Enter your username" v-model="username" required />
      </div>
      <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" id="password" placeholder="Enter your password" v-model="password" required />
      </div>
      <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" id="email" placeholder="Enter your Email" v-model="email" required />
      </div>
      <button type="submit" class="register-button">
        <router-link to="/login" class="register-button">Register</router-link>
      </button>
    </form>
  </div>
</template>

<script>
import { new_user } from "../api/index.js";

export default {
  data() {
    return {
      username: '',
      password: '',
      email: ''
    };
  },
  methods: {
    handleRegister() {
      console.log('Username:', this.username);
      console.log('Password:', this.password);
      console.log('Email:', this.email);
      new_user(this.username, this.email, this.password);
    }
  }
};
</script>

<style>
.register-page {
  max-width: 400px;
  margin: 0 auto;
  padding: 20px;
  background-color: #1e1e1e;
  border-radius: 5px;
  color: white;
}

.form-group {
  margin-bottom: 15px;
  display: flex;
  flex-direction: column;
  /* Stack label above input */
}

label {
  font-weight: bold;
  margin-bottom: 5px;
  /* Space between label and input */
}

input {
  width: 100%;
  padding: 8px;
  border: none;
  border-radius: 5px;
  background-color: #333;
  color: white;
  box-sizing: border-box;
}

input:focus {
  outline: none;
  border: 2px solid #bb86fc;
}

.register-button {
  width: 100%;
  padding: 10px;
  background-color: #bb86fc;
  color: white;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  font-size: 1.1em;
}

button:hover {
  background-color: #03dac6;
}
</style>
